// ── OHUD Dental — treatment data (single source of truth) ──
// Used by the homepage service cards and the dynamic /treatments/[slug] pages.

// Stable Pexels CDN URL for a verified dental photo id.
export function px(id, w, h) {
  return `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${h}`;
}
export function fallback(w, h) {
  return `https://placehold.co/${w}x${h}/15232E/1EB6A8?text=OHUD+Dental`;
}

// Feature icons (raw SVG strings, rendered via dangerouslySetInnerHTML)
export const icons = {
  check: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>`,
  tooth: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 5.5c-1.7-1.6-3.3-2-5-2C4.5 3.5 3 5.4 3 8c0 2 .6 3.4 1.2 6 .5 2.2 1 4.5 2.3 4.5 1.2 0 1.4-2 1.7-3.7.3-1.6.6-3.3 1.8-3.3s1.5 1.7 1.8 3.3c.3 1.7.5 3.7 1.7 3.7 1.3 0 1.8-2.3 2.3-4.5.6-2.6 1.2-4 1.2-6 0-2.6-1.5-4.5-4-4.5-1.7 0-3.3.4-5 2z"/></svg>`,
  sparkle: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9L12 3z"/></svg>`,
  clock: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/></svg>`,
  smile: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M8 14s1.5 2 4 2 4-2 4-2"/><line x1="9" y1="9" x2="9.01" y2="9"/><line x1="15" y1="9" x2="15.01" y2="9"/></svg>`,
  shield: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
  star: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.1 8.6 22 9.3 17 14.1 18.2 21 12 17.8 5.8 21 7 14.1 2 9.3 8.9 8.6 12 2"/></svg>`,
  heart: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1a5.5 5.5 0 0 0-7.8 7.8l1.1 1L12 21l7.8-7.8 1-1a5.5 5.5 0 0 0 0-7.6z"/></svg>`,
  scan: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/><line x1="7" y1="12" x2="17" y2="12"/></svg>`,
  leaf: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10z"/><path d="M2 21c0-3 1.85-5.36 5.08-6"/></svg>`,
  phone: `<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>`,
};

export const services = [
  {
    slug: 'general-dentistry',
    nav: 'General & Family Dentistry',
    short: 'Check-ups, cleaning, fillings and preventive care for the whole family.',
    titleHtml: 'General & <span>Family</span> Dentistry',
    title: 'General & Family Dentistry',
    tag: 'Preventive Care',
    heroId: 3881296,
    lead: 'Healthy smiles start with consistent, gentle care. Our general dentistry keeps every member of your family — from toddlers to grandparents — comfortable, cavity-free, and confident.',
    rows: [
      { tag: 'Routine Examinations', heading: 'Catch Problems Early, Before They Hurt', imgId: 6812570, rev: false,
        paras: ['Every visit begins with a thorough examination of your teeth, gums, bite and soft tissues. Using low-radiation digital X-rays where needed, we spot cavities, gum disease and other concerns at the earliest stage — when treatment is simplest, gentlest and most affordable.'],
        bullets: ['Comfortable six-monthly check-ups', 'Low-radiation digital X-rays', 'Oral cancer screening', 'Personalised home-care advice'] },
      { tag: 'Cleaning & Fillings', heading: 'A Fresh, Clean, Protected Smile', imgId: 5355694, rev: true,
        paras: ['No matter how well you brush, hardened plaque builds up over time. Our hygienists gently remove it with professional scaling and polishing, leaving your mouth fresh and protected.', 'When a cavity does appear, we restore it with natural, tooth-coloured composite fillings — mercury-free and virtually invisible.'],
        bullets: ['Professional scaling & polishing', 'Tooth-coloured composite fillings', 'Fluoride treatment & sealants for kids'] },
    ],
    features: [
      { icon: 'check', name: 'Pain-Free Approach', text: 'Gentle techniques and a calm setting keep even nervous patients relaxed.' },
      { icon: 'heart', name: 'Family-Friendly', text: 'One trusted clinic for every age — from first tooth to golden years.' },
      { icon: 'scan', name: 'Digital X-Rays', text: 'Up to 80% less radiation with instant, highly accurate images.' },
      { icon: 'clock', name: 'Short Wait Times', text: 'Punctual appointments that respect your busy schedule.' },
    ],
    strip: [
      { big: '6 mo', h3: 'Recommended Recall', p: 'Twice-yearly check-ups keep small issues from becoming big, painful ones.' },
      { big: '15 min', h3: 'Average Cleaning', p: 'Quick, comfortable scaling and polishing that fits into your day.' },
      { big: 'All ages', h3: 'Whole Family', p: 'Children, adults and seniors all cared for under one roof.' },
    ],
    related: ['teeth-whitening', 'gum-treatment', 'pediatric-dentistry'],
  },
  {
    slug: 'cosmetic-dentistry',
    nav: 'Cosmetic Dentistry',
    short: 'Veneers, smile makeovers and bonding for a brighter, natural smile.',
    titleHtml: 'Cosmetic <span>Dentistry</span>',
    title: 'Cosmetic Dentistry',
    tag: 'Smile Design',
    heroId: 12934843,
    lead: 'A confident smile changes how you look and feel. Our cosmetic treatments deliver natural, beautiful results — designed around your face, your goals and your lifestyle.',
    rows: [
      { tag: 'Porcelain Veneers', heading: 'Instantly Correct Chips, Gaps & Stains', imgId: 6528858, rev: false,
        paras: ['Ultra-thin, custom-made porcelain shells are bonded to the front of your teeth to correct chips, gaps, stubborn discolouration and minor misalignment. Crafted to match your natural enamel, they look and feel completely real.'],
        bullets: ['Custom-shaded to suit your face', 'Minimal tooth preparation', 'Stain-resistant, long-lasting porcelain'] },
      { tag: 'Smile Makeovers', heading: 'A Smile You Will Love to Show Off', imgId: 5842006, rev: true,
        paras: ['For a complete transformation, we combine whitening, veneers, bonding and reshaping into one coordinated plan. Using digital previews, you can see your future smile before any treatment starts — so the result is exactly what you imagined.'],
        bullets: ['Digital smile preview', 'Coordinated multi-treatment plan', 'Natural, never artificial results'] },
    ],
    features: [
      { icon: 'sparkle', name: 'Natural Aesthetics', text: 'Results designed to look effortlessly real — never fake or bulky.' },
      { icon: 'smile', name: 'Confidence Boost', text: 'A smile you will not want to hide in photos or meetings.' },
      { icon: 'star', name: 'Premium Materials', text: 'High-grade porcelain and composites for lasting beauty.' },
      { icon: 'scan', name: 'Digital Design', text: 'Preview your new smile in 3D before you commit.' },
    ],
    strip: [
      { big: '2–3', h3: 'Visits for Veneers', p: 'Most veneer cases are completed comfortably in a few appointments.' },
      { big: 'Custom', h3: 'Shade Matching', p: 'Every restoration is matched to your desired brightness and tone.' },
      { big: 'Easy', h3: 'Installment Plans', p: 'Spread the cost of your smile makeover over manageable months.' },
    ],
    related: ['teeth-whitening', 'orthodontics', 'general-dentistry'],
  },
  {
    slug: 'orthodontics',
    nav: 'Braces & Clear Aligners',
    short: 'Straighten teeth with braces or near-invisible clear aligners.',
    titleHtml: 'Braces & <span>Clear Aligners</span>',
    title: 'Braces & Clear Aligners',
    tag: 'Orthodontics',
    heroId: 5524021,
    lead: 'Straight teeth are easier to clean, healthier, and give you a bite that works comfortably for life. We offer the full range of options for children, teens and adults.',
    rows: [
      { tag: 'Braces', heading: 'Reliable Results for Every Case', imgId: 19147369, rev: false,
        paras: ['Traditional and ceramic braces are highly effective for correcting crowding, gaps and complex bite problems. Ceramic braces use tooth-coloured brackets for a far more discreet appearance, and remain the most cost-effective route to a straight smile.'],
        bullets: ['Metal & tooth-coloured ceramic options', 'Ideal for complex alignment', 'Most affordable orthodontic choice'] },
      { tag: 'Clear Aligners', heading: 'Straighten Discreetly, Live Freely', imgId: 3845985, rev: true,
        paras: ['Virtually invisible, removable aligner trays gradually move your teeth into place. They are comfortable, easy to clean, and let you eat whatever you like — a favourite among adults and working professionals who prefer a subtle treatment.'],
        bullets: ['Nearly invisible & removable', 'Eat and brush normally', 'Comfortable, smooth-edged trays'] },
    ],
    features: [
      { icon: 'smile', name: 'Free Assessment', text: 'We examine your teeth and recommend the best option for you.' },
      { icon: 'star', name: 'Adult & Teen', text: 'Discreet options designed for grown-ups, not just children.' },
      { icon: 'scan', name: 'Digital Planning', text: 'Map your tooth movements precisely from day one.' },
      { icon: 'clock', name: 'Flexible Plans', text: 'Easy monthly installments make treatment affordable.' },
    ],
    strip: [
      { big: '12–24 mo', h3: 'Typical Duration', p: 'Most cases finish within one to two years, depending on complexity.' },
      { big: 'Free', h3: 'First Consultation', p: 'Get a clear plan and quote before you decide anything.' },
      { big: 'Any age', h3: 'Never Too Late', p: 'Adults straighten their smiles here every single week.' },
    ],
    related: ['cosmetic-dentistry', 'general-dentistry', 'pediatric-dentistry'],
  },
  {
    slug: 'dental-implants',
    nav: 'Dental Implants',
    short: 'Permanent, natural-looking replacements for missing teeth.',
    titleHtml: 'Dental <span>Implants</span>',
    title: 'Dental Implants',
    tag: 'Tooth Replacement',
    heroId: 6812500,
    lead: 'Missing teeth affect your confidence, speech and ability to enjoy food. Dental implants are the gold-standard, permanent solution — looking, feeling and working just like natural teeth.',
    rows: [
      { tag: 'What Is an Implant?', heading: 'A New Tooth, Rooted for Life', imgId: 6502305, rev: false,
        paras: ['An implant is a small, biocompatible titanium post placed into the jawbone to replace a missing tooth root. Once healed, it supports a custom crown, bridge or denture that is firmly fixed in place — with no slipping and no adhesives.'],
        bullets: ['Premium titanium implant systems', 'Custom crown matched to your teeth', 'Restores full chewing power'] },
      { tag: 'Precision Planning', heading: 'Placed Accurately, Healed Comfortably', imgId: 6529219, rev: true,
        paras: ['We use 3D digital planning for accurate, predictable placement, whether you are missing a single tooth or several. Implant-supported bridges and dentures can restore an entire arch with remarkable stability and comfort.'],
        bullets: ['3D-guided implant placement', 'Single, multiple or full-arch options', 'Long-lasting — often for decades'] },
    ],
    features: [
      { icon: 'tooth', name: 'Looks Natural', text: 'Indistinguishable from your real teeth, even up close.' },
      { icon: 'shield', name: 'Built to Last', text: 'With good care, implants can last for many decades.' },
      { icon: 'scan', name: '3D Guided', text: 'Digital planning for precise, predictable, safe placement.' },
      { icon: 'check', name: 'Eat Anything', text: 'Bite and chew with full, natural confidence again.' },
    ],
    strip: [
      { big: '1 tooth', h3: 'To Full Arch', p: 'Replace a single gap or an entire row with fixed teeth.' },
      { big: 'Titanium', h3: 'Certified Implants', p: 'Internationally approved systems for proven reliability.' },
      { big: 'Easy', h3: 'Installment Plans', p: 'Restore your smile without the financial stress.' },
    ],
    related: ['root-canal', 'general-dentistry', 'cosmetic-dentistry'],
  },
  {
    slug: 'root-canal',
    nav: 'Root Canal Treatment',
    short: 'Pain-free endodontics that saves your natural tooth.',
    titleHtml: 'Pain-Free <span>Root Canal</span> Treatment',
    title: 'Pain-Free Root Canal Treatment',
    tag: 'Endodontics',
    heroId: 16903641,
    lead: 'A severe toothache often means the nerve inside a tooth is infected. Root canal treatment removes the infection, ends the pain, and saves your natural tooth — so you do not lose it.',
    rows: [
      { tag: 'Modern Endodontics', heading: 'Far Gentler Than Its Reputation', imgId: 4687906, rev: false,
        paras: ['Forget the scary myths. With effective local anaesthesia and modern rotary instruments, a root canal at OHUD Dental feels much like a routine filling. Most patients are genuinely amazed at how comfortable and quick it is.'],
        bullets: ['Effective, profound numbing', 'Precise rotary instrumentation', 'Often completed in a single visit'] },
      { tag: 'Save Your Tooth', heading: 'Keep What Nature Gave You', imgId: 19328507, rev: true,
        paras: ['Keeping your own tooth is almost always better than extraction. Root canal treatment preserves your natural bite, appearance and chewing function. Afterwards we usually protect the tooth with a crown to restore its full strength.'],
        bullets: ['Preserves your natural tooth', 'Protected with a durable crown', 'Ends throbbing pain & sensitivity'] },
    ],
    features: [
      { icon: 'check', name: 'Truly Pain-Free', text: 'Comfortable, anaesthetised treatment from start to finish.' },
      { icon: 'clock', name: 'Single Visit', text: 'Many cases are completed in just one appointment.' },
      { icon: 'tooth', name: 'Tooth Saved', text: 'Avoid extraction and keep your natural smile intact.' },
      { icon: 'heart', name: 'Fast Relief', text: 'Stops the throbbing pain of an infected nerve quickly.' },
    ],
    strip: [
      { big: '1 visit', h3: 'Often Enough', p: 'Most root canals are finished comfortably in one sitting.' },
      { big: 'Same-day', h3: 'Pain Relief', p: 'Walk in with toothache, walk out with relief.' },
      { big: 'Crown', h3: 'Full Protection', p: 'A crown restores the tooth to full strength afterwards.' },
    ],
    related: ['dental-implants', 'general-dentistry', 'emergency-care'],
  },
  {
    slug: 'teeth-whitening',
    nav: 'Teeth Whitening',
    short: 'Safe, professional whitening that brightens your smile by several shades.',
    titleHtml: 'Professional <span>Teeth Whitening</span>',
    title: 'Professional Teeth Whitening',
    tag: 'Cosmetic',
    heroId: 5622271,
    lead: 'Years of tea, coffee and everyday foods leave teeth dull and stained. Professional whitening safely brightens your smile by several shades — with results far beyond any over-the-counter kit.',
    rows: [
      { tag: 'In-Clinic Whitening', heading: 'Dramatic Results in About an Hour', imgId: 6627284, rev: false,
        paras: ['Our supervised in-clinic treatment delivers a noticeably brighter smile in around an hour. Because it is performed by professionals, your gums and enamel are fully protected throughout — for fast results without the risk.'],
        bullets: ['Visible results in one session', 'Gums fully protected', 'Clinically proven whitening gel'] },
      { tag: 'Take-Home Kits', heading: 'Brighten at Your Own Pace', imgId: 12934843, rev: true,
        paras: ['Prefer to whiten gradually? We provide custom-fitted trays and professional-grade gel so you can safely brighten at home, with our guidance. Unlike charcoal pastes and unregulated kits, our whitening is gentle and tailored to your sensitivity.'],
        bullets: ['Custom-fitted trays', 'Professional-grade gel', 'Tailored to your sensitivity level'] },
    ],
    features: [
      { icon: 'sparkle', name: 'Several Shades', text: 'A brighter, fresher smile that genuinely shows.' },
      { icon: 'shield', name: 'Enamel-Safe', text: 'Dentist-supervised gels protect your teeth and gums.' },
      { icon: 'clock', name: 'Quick Session', text: 'In-clinic whitening in roughly one hour.' },
      { icon: 'smile', name: 'Even Results', text: 'Uniform brightness — no patchy or grey tones.' },
    ],
    strip: [
      { big: '~1 hr', h3: 'In-Clinic Session', p: 'A brighter smile during a single lunch break.' },
      { big: 'Safe', h3: 'Dentist-Supervised', p: 'Far safer and more effective than DIY trends.' },
      { big: 'Lasting', h3: 'With Maintenance', p: 'Simple aftercare keeps your results bright for longer.' },
    ],
    related: ['cosmetic-dentistry', 'general-dentistry', 'orthodontics'],
  },
  {
    slug: 'pediatric-dentistry',
    nav: "Children's Dentistry",
    short: 'Gentle, friendly dental care that children actually enjoy.',
    titleHtml: "Children's <span>Dentistry</span>",
    title: "Children's Dentistry",
    tag: 'Kids & Teens',
    heroId: 8224633,
    lead: 'Happy early dental experiences set children up for a lifetime of healthy smiles. Our team makes every visit gentle, friendly and even fun — so your little ones feel safe, not scared.',
    rows: [
      { tag: 'Gentle Care', heading: 'Building Trust, One Smile at a Time', imgId: 8260438, rev: false,
        paras: ['We take extra time to build trust, explain things in simple words and keep treatments comfortable. Our goal is for kids to genuinely enjoy coming to the dentist — turning anxious first visits into happy routines.'],
        bullets: ['Patient, child-friendly approach', 'Calm, welcoming environment', 'Parents welcome throughout'] },
      { tag: 'Prevention First', heading: 'Protect Little Teeth as They Grow', imgId: 7800568, rev: true,
        paras: ['Fluoride treatments and protective sealants shield young teeth from decay, while regular check-ups catch issues early and teach great brushing habits. We also monitor developing teeth and jaws to advise on orthodontics at the right time.'],
        bullets: ['Fluoride & protective sealants', 'Early orthodontic monitoring', 'Fun brushing & diet coaching'] },
    ],
    features: [
      { icon: 'heart', name: 'Kind & Patient', text: 'A caring team who genuinely loves treating children.' },
      { icon: 'shield', name: 'Decay Defence', text: 'Sealants and fluoride that keep cavities away.' },
      { icon: 'smile', name: 'Fun Visits', text: 'Positive experiences that build lifelong habits.' },
      { icon: 'check', name: 'Growth Tracking', text: 'We watch developing smiles and advise early.' },
    ],
    strip: [
      { big: 'Age 1+', h3: 'First Visit', p: 'Early visits build comfort and catch issues sooner.' },
      { big: 'Sealants', h3: 'Cavity Shield', p: 'A simple, painless layer of protection for molars.' },
      { big: 'Fun', h3: 'Friendly Team', p: 'Kids leave smiling — and actually ask to come back.' },
    ],
    related: ['general-dentistry', 'orthodontics', 'emergency-care'],
  },
  {
    slug: 'emergency-care',
    nav: 'Emergency Dentistry',
    short: 'Prompt relief for toothache, broken teeth and dental swelling.',
    titleHtml: 'Emergency <span>Dentistry</span>',
    title: 'Emergency Dentistry',
    tag: 'Urgent Care',
    heroId: 16430835,
    lead: 'Dental emergencies are painful and stressful — and they rarely happen at a convenient time. We offer prompt care to relieve your pain and protect your teeth as quickly as possible.',
    rows: [
      { tag: 'Severe Toothache', heading: 'Fast Diagnosis, Fast Relief', imgId: 5355715, rev: false,
        paras: ['Throbbing or constant tooth pain usually signals infection or a deep cavity. We diagnose the cause quickly and provide immediate relief, often with same-day treatment, so you are not left suffering.'],
        bullets: ['Same-day emergency slots', 'Immediate pain relief', 'Clear next-step treatment plan'] },
      { tag: 'Trauma & Swelling', heading: 'Acting Quickly Can Save a Tooth', imgId: 20301626, rev: true,
        paras: ['A knocked-out or fractured tooth can often be saved if you act fast — keep the tooth moist and contact us right away. Facial swelling and abscesses need urgent attention to stop infection spreading; we treat the source and prescribe the right medication.'],
        bullets: ['Broken & knocked-out teeth', 'Abscess & swelling management', 'Sunday & after-hours on request'] },
    ],
    features: [
      { icon: 'clock', name: 'Seen Quickly', text: 'Priority emergency appointments when you need them.' },
      { icon: 'phone', name: 'Call or WhatsApp', text: 'Reach us fast on +92 300 1234567 for urgent help.' },
      { icon: 'shield', name: 'Tooth-Saving', text: 'Rapid action gives the best chance of saving a tooth.' },
      { icon: 'heart', name: 'Calm Care', text: 'Reassuring treatment when you are stressed and in pain.' },
    ],
    strip: [
      { big: 'Same-day', h3: 'Urgent Slots', p: 'We keep time aside daily for genuine emergencies.' },
      { big: 'Sun', h3: 'On Request', p: 'After-hours and Sunday emergency care available.' },
      { big: 'Act fast', h3: 'Save the Tooth', p: 'The sooner you call, the more we can do.' },
    ],
    related: ['root-canal', 'general-dentistry', 'dental-implants'],
  },
  {
    slug: 'gum-treatment',
    nav: 'Gum Treatment',
    short: 'Keep your gums strong and your teeth secure with periodontal care.',
    titleHtml: 'Gum Treatment <span>(Periodontics)</span>',
    title: 'Gum Treatment (Periodontics)',
    tag: 'Periodontics',
    heroId: 6528858,
    lead: 'Healthy gums are the foundation of a healthy smile. Gum disease is one of the most common — and most overlooked — dental problems, and left untreated it can lead to tooth loss.',
    rows: [
      { tag: 'Early Signs', heading: 'Catch Gum Disease Before It Spreads', imgId: 16430835, rev: false,
        paras: ['Bleeding when brushing, persistent bad breath and red or swollen gums are early warning signs. Caught early, gum disease is easily managed with professional cleaning and improved home care — protecting both your gums and your teeth.'],
        bullets: ['Gum health assessment', 'Bleeding & bad-breath review', 'Tailored home-care coaching'] },
      { tag: 'Deep Cleaning', heading: 'Help Your Gums Heal & Reattach', imgId: 3845745, rev: true,
        paras: ['For more advanced cases, we gently remove plaque and tartar from below the gum line and smooth the root surfaces (scaling and root planing), helping your gums heal and reattach to the teeth. A personalised maintenance plan keeps it under control long-term.'],
        bullets: ['Scaling & root planing', 'Below-the-gumline cleaning', 'Ongoing maintenance schedule'] },
    ],
    features: [
      { icon: 'shield', name: 'Protect Teeth', text: 'Healthy gums keep your teeth firmly anchored.' },
      { icon: 'leaf', name: 'Fresher Breath', text: 'Treating gum disease tackles the cause of bad breath.' },
      { icon: 'check', name: 'Early Action', text: 'Caught early, gum disease is simple to reverse.' },
      { icon: 'heart', name: 'Whole-Body Link', text: 'Gum health is linked to your overall wellbeing.' },
    ],
    strip: [
      { big: 'Reversible', h3: 'When Early', p: 'Early-stage gum disease responds quickly to treatment.' },
      { big: 'Deep clean', h3: 'For Advanced', p: 'Scaling and root planing for established disease.' },
      { big: 'Ongoing', h3: 'Maintenance', p: 'A simple recall plan keeps your gums healthy for life.' },
    ],
    related: ['general-dentistry', 'teeth-whitening', 'dental-implants'],
  },
];

export const bySlug = Object.fromEntries(services.map((s) => [s.slug, s]));

// ── Dental team (shared by /team and the homepage preview strip) ──
export const team = [
  { photo: 19438560, name: 'Dr. Saad Mahmood', role: 'Founder & Lead Implantologist', bio: 'With over 18 years of experience and advanced implant training abroad, Dr. Saad founded OHUD Dental to bring world-class, gentle dentistry to Lahore.', tags: ['Dental Implants', 'Oral Surgery'] },
  { photo: 7904406, name: 'Dr. Hira Naqvi', role: 'Cosmetic & Restorative Dentist', bio: 'A specialist in smile design, Dr. Hira crafts natural-looking veneers, bonding and full smile makeovers tailored to each patient’s features.', tags: ['Veneers', 'Whitening', 'Bonding'] },
  { photo: 6762869, name: 'Dr. Faisal Khan', role: 'Consultant Orthodontist', bio: 'Dr. Faisal straightens smiles of all ages with traditional braces, ceramic braces and clear aligners — known for his patience with anxious teens.', tags: ['Braces', 'Clear Aligners'] },
  { photo: 8376306, name: 'Dr. Mariam Aslam', role: 'Endodontist (Root Canal Specialist)', bio: 'Using modern rotary technology, Dr. Mariam performs truly pain-free root canals — saving natural teeth comfortably, often in a single visit.', tags: ['Root Canal', 'Tooth Preservation'] },
  { photo: 3881440, name: 'Dr. Zainab Qureshi', role: 'Paediatric Dentist', bio: 'Warm, playful and endlessly patient, Dr. Zainab makes dental visits fun for children and builds healthy habits that last a lifetime.', tags: ["Children's Dentistry", 'Preventive Care'] },
  { photo: 10695742, name: 'Dr. Omar Farooq', role: 'Periodontist & Oral Surgeon', bio: 'Dr. Omar treats gum disease and performs surgical procedures with precision and care, keeping the foundations of your smile strong and healthy.', tags: ['Gum Treatment', 'Surgery'] },
];
